name: 每30分钟更新直播源
on:
  schedule:
    cron: '*/30 * * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dep
        run: pip install requests

      - name: Run crawl
        run: python crawl.py

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add tv.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update tv.m3u $(date +'%Y-%m-%d %H:%M')"
          git push
